spring.application.name=openai-client-security-demo

server.port=8080

chatgpt.api.key=${OPENAI_API_KEY}
chatgpt.api.baseUrl=https://api.openai.com/v1
weather.api.baseUrl=https://api.open-meteo.com/v1
geocoding.api.baseUrl=https://geocoding-api.open-meteo.com/v1

logging.level.ek.osnb.demo=TRACE