spring.application.name=openai-client-security-demo

server.port=8080

app.ai.openai.model=gpt-4.1
app.ai.openai.max-output-tokens=800
app.ai.openai.baseUrl=https://api.openai.com/v1
app.ai.openai.apiKey=${OPENAI_API_KEY}

external.api.weather.baseUrl=https://api.open-meteo.com/v1
external.api.geocoding.baseUrl=https://geocoding-api.open-meteo.com/v1

logging.level.ek.osnb.demo=TRACE