spring.application.name=openai-client-security-demo

server.port=8080

app.ai.provider=openai
app.ai.model=gpt-4.1
app.ai.max-output-tokens=800
app.ai.base-url=https://api.openai.com
app.ai.api-key=${OPENAI_API_KEY}

external.api.weather.baseUrl=https://api.open-meteo.com/v1
external.api.geocoding.baseUrl=https://geocoding-api.open-meteo.com/v1

logging.level.ek.osnb.demo=TRACE